module.exports = {
  UPDATE_STORE: 'UPDATE_STORE' //,
  // STATION_LOADING: 'STATION_LOADING',
  // STATION_UPDATE: 'STATION_UPDATE',
  // SONG_LOADING: 'SONG_LOADING',
  // SONG_UPDATE: 'SONG_UPDATE',
  // CONSTRAINT_LOADING: 'CONSTRAINT_LOADING',
  // CONSTRAINT_UPDATE: 'CONSTRAINT_UPDATE'
};
